dist: xenial
language: python
python:
  - '3.7'

branches:
  only:
    - staging

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

env:
  - ENV="TEST" DJANGO_SETTINGS_MODULE="pur_beurre.settings"

services:
  - postgresql

script:
  - 'pytest'